# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# load rules
# -----------------------------------------------------
include: "rules/common.smk"
include: "rules/get_fastq.smk"
include: "rules/trim.smk"
include: "rules/umi_extraction.smk"
include: "rules/qc.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    default_target: True
    input:
        "results/multiqc/multiqc_report.html",
