$schema: "https://json-schema.org/draft/2020-12/schema"
description: configuration file for the analysis pipeline
properties:
  samplesheet:
    type: string
    description: path to the sample sheet in tsv format
  get_genome:
    type: object
    properties:
      database:
        type: string
        description: database to use for genome retrieval, 'ncbi' or 'manual'
        default: ncbi
      assembly:
        type: string
        description: RefSeq assembly accession to use for genome retrieval
        default: GCF_000307535.1
      fasta:
        type: [string, "null"]
        description: path to a custom FASTA file (optional)
      gff:
        type: [string, "null"]
        description: path to a custom GFF file (optional)
      gff_source_type:
        type: array
        description: mapping of GFF source types to feature types
    required:
      - database
      - assembly
      - gff_source_type
  processing:
    type: object
    properties:
      tool:
        type: string
        description: processing tool to use, one of 'fastp' or 'fastplong'
        default: fastp
      fastp:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to fastp
      fastplong:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to fastplong
    required:
      - tool
  mapping:
    type: object
    properties:
      tool:
        type: string
        description: mapping tool to use, one of 'bowtie2', 'bwa_mem2', 'star', or 'minimap2'
        default: bwa_mem2
      bowtie2:
        type: object
        properties:
          index:
            type: string
            description: additional arguments to bowtie build
          extra:
            type: string
            description: additional arguments to bowtie align
      bwa_mem2:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to bwa-mem2
          sort:
            type: string
            description: sorting tool to use, e.g. 'samtools'
            default: samtools
          sort_order:
            type: string
            description: sorting order to use
            default: coordinate
          sort_extra:
            type: string
            description: additional arguments to pass to the sorting tool
      star:
        type: object
        properties:
          index:
            type: string
            description: additional arguments to STAR index
          extra:
            type: array
            items:
              type: string
            description: additional arguments to STAR align
            default:
              [
                "--outFilterMultimapNmax 10",
                "--outSAMmultNmax 1",
                "--outMultimapperOrder Random",
                "--alignIntronMax 1",
              ]
      minimap2:
        type: object
        properties:
          index:
            type: string
            description: additional arguments to minimap2 index
          extra:
            type: string
            description: additional arguments to minimap2 align
            default: -ax map-ont
          sorting:
            type: string
            description: sorting order to use
            default: coordinate
          sort_extra:
            type: string
            description: additional arguments to pass to the sorting tool
      samtools_sort:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to Samtools sort
            default: -m 4G
      samtools_index:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to Samtools index
    required:
      - tool
  mapping_stats:
    type: object
    properties:
      gffread:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to GFFread
      rseqc_infer_experiment:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to RSeQC infer_experiment.py
      rseqc_bam_stat:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to RSeQC bam_stat.py
      deeptools_coverage:
        type: object
        properties:
          genome_size:
            type: integer
            description: genome size in base pairs
            default: 1000
          extra:
            type: string
            description: additional arguments to pass to DeepTools bamCoverage
      deeptools_plotcoverage:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to DeepTools plotCoverage
    required:
      - gffread
      - rseqc_infer_experiment
      - rseqc_bam_stat
      - deeptools_coverage
  variant_calling:
    type: object
    properties:
      tool:
        type: [string, array]
        description: the variant caller to use, one of 'freebayes', 'bcftools', or both
      bcftools_pileup:
        type: object
        properties:
          uncompressed:
            type: boolean
            description: whether to output uncompressed BCF files
            default: false
          extra:
            type: string
            description: additional arguments to pass to BCFtools pileup
      bcftools_call:
        type: object
        properties:
          uncompressed:
            type: boolean
            description: whether to output uncompressed VCF files
            default: false
          caller:
            type: string
            description: use '-c' for consensus or '-m' for multiallelic
            default: "-c"
          extra:
            type: string
            description: additional arguments to pass to BCFtools call
      bcftools_view:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to BCFtools view
      bcftools_filter:
        type: object
        properties:
          filter:
            type: string
            description: expression used to filter BCF/VCF records
            default: '-e ''ALT="."'''
          extra:
            type: string
            description: additional arguments to pass to BCFtools filter
      freebayes:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to Freebayes call
    required:
      - bcftools_pileup
      - bcftools_call
      - bcftools_view
      - bcftools_filter
      - freebayes
  variant_annotation:
    type: object
    properties:
      tool:
        type: string
        description: annotation tool to use, one of 'vep', 'snpeff'
        default: vep
      vep:
        type: object
        properties:
          convert_gff:
            type: boolean
            description: whether to convert NCBI GFF to Ensembl-style GFF for VEP compatibility
            default: true
          plugins:
            type: array
            description: list of VEP plugins to use
            default: []
            items:
              type: string
          extra:
            type: string
            description: additional arguments to pass to VEP
      snpeff:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to SnpEff
    required:
      - tool
      - vep
      - snpeff

  qc:
    type: object
    properties:
      multiqc:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to MultiQC
      fastqc:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to FastQC
    required:
      - multiqc
      - fastqc
  report:
    type: object
    properties:
      minimum_variant_count:
        type: integer
        description: minimum number of samples/appearances for the same variant to be included in the final report
required:
  - samplesheet
  - get_genome
  - processing
  - mapping
  - mapping_stats
  - variant_calling
  - variant_annotation
  - qc
  - report
