$schema: "https://json-schema.org/draft/2020-12/schema"
description: configuration file for the analysis pipeline
properties:
  samplesheet:
    type: string
    description: path to the sample sheet in tsv format

  trimming:
    type: object
    properties:
      tool:
        type: string
        description: processing tool to use, one of 'fastp' or 'fastplong'
        default: fastp
      fastp:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to fastp
      fastplong:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to fastplong
    required:
      - tool

  qc:
    type: object
    properties:
      multiqc:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to MultiQC
      fastqc:
        type: object
        properties:
          extra:
            type: string
            description: additional arguments to pass to FastQC
    required:
      - multiqc
      - fastqc

required:
  - samplesheet
  - trimming
  - qc