samplesheet: "config/samples.tsv"

get_fastq:
  PE: True
  tool: "fasterq_dump"
  fastq_dump:
    extra: "-X 10000"
  fasterq_dump:
    extra: ""
    
trimming:
  tool: "fastp"
  fastp:
    extra: ""
  fastplong:
    extra: ""

umi_extraction:
  enabled: false  # Set to true to enable UMI extraction
  tool: "umi_tools"
  umi_tools:
    extra: ""

qc:
  multiqc:
    extra: "--verbose --dirs"
  fastqc:
    extra: "--quiet"
